---
- hosts: all
  gather_facts: false

  vars:
    use_python3: "{{ lookup('env', 'ANSIBLE_PYTHON_VERSION') == '3' }}"

  roles:
    - bbatsche.Base
    - role: geerlingguy.swap
      become: yes
      when:
        - ansible_connection | default('smart') != 'local'
        - ansible_connection | default('smart') != 'docker'

  pre_tasks:
    - name: Install Python for Ansible
      raw: >
        bash -c "test -e /usr/bin/python{{ "3" if use_python3 else "" }} ||
        (apt -qqy update && apt install -qqy python{{ "3" if use_python3 else "" }}-minimal)"
      become: yes
      register: output
      changed_when:
        - output.stdout != ""
        - output.stdout != "\r\n"

    - name: Gathering Facts
      setup:

  tasks:
    - name: Always Expand Bash Aliases
      copy:
        content: shopt -s expand_aliases;
        dest: /etc/profile.d/alias.sh
      become: yes

    - name: Accept All Environment Variables from SSH
      lineinfile:
        line: AcceptEnv *
        regexp: ^AcceptEnv
        dest: /etc/ssh/sshd_config
        validate: /usr/sbin/sshd -t -f %s
      become: yes
      notify: Restart SSH
      when:
        - ansible_connection | default('smart') != 'local'
        - ansible_connection | default('smart') != 'docker'

    - name: Install Spec Dependencies
      apt:
        name:
          - lsb-release
          - lsb-core
          - netcat
          - net-tools
          - iproute2
        state: present
        update_cache: yes
        cache_valid_time: 86400
      become: yes

  handlers:
    - name: Restart SSH
      service: name=ssh state=restarted
      become: yes
